package my.instagram.bean;

import java.util.Date;

public class InstaAccess {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insta_access.userid
     *
     * @mbggenerated Thu Nov 16 17:15:53 KST 2017
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insta_access.access_token
     *
     * @mbggenerated Thu Nov 16 17:15:53 KST 2017
     */
    private String accessToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insta_access.username
     *
     * @mbggenerated Thu Nov 16 17:15:53 KST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insta_access.user
     *
     * @mbggenerated Thu Nov 16 17:15:53 KST 2017
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insta_access.regdate
     *
     * @mbggenerated Thu Nov 16 17:15:53 KST 2017
     */
    private Date regdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insta_access.userid
     *
     * @return the value of insta_access.userid
     *
     * @mbggenerated Thu Nov 16 17:15:53 KST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insta_access.userid
     *
     * @param userid the value for insta_access.userid
     *
     * @mbggenerated Thu Nov 16 17:15:53 KST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insta_access.access_token
     *
     * @return the value of insta_access.access_token
     *
     * @mbggenerated Thu Nov 16 17:15:53 KST 2017
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insta_access.access_token
     *
     * @param accessToken the value for insta_access.access_token
     *
     * @mbggenerated Thu Nov 16 17:15:53 KST 2017
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insta_access.username
     *
     * @return the value of insta_access.username
     *
     * @mbggenerated Thu Nov 16 17:15:53 KST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insta_access.username
     *
     * @param username the value for insta_access.username
     *
     * @mbggenerated Thu Nov 16 17:15:53 KST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insta_access.user
     *
     * @return the value of insta_access.user
     *
     * @mbggenerated Thu Nov 16 17:15:53 KST 2017
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insta_access.user
     *
     * @param user the value for insta_access.user
     *
     * @mbggenerated Thu Nov 16 17:15:53 KST 2017
     */
    public void setUser(String user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insta_access.regdate
     *
     * @return the value of insta_access.regdate
     *
     * @mbggenerated Thu Nov 16 17:15:53 KST 2017
     */
    public Date getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insta_access.regdate
     *
     * @param regdate the value for insta_access.regdate
     *
     * @mbggenerated Thu Nov 16 17:15:53 KST 2017
     */
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }
}