package my.random.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DestinyInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public DestinyInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGnoIsNull() {
            addCriterion("gno is null");
            return (Criteria) this;
        }

        public Criteria andGnoIsNotNull() {
            addCriterion("gno is not null");
            return (Criteria) this;
        }

        public Criteria andGnoEqualTo(Integer value) {
            addCriterion("gno =", value, "gno");
            return (Criteria) this;
        }

        public Criteria andGnoNotEqualTo(Integer value) {
            addCriterion("gno <>", value, "gno");
            return (Criteria) this;
        }

        public Criteria andGnoGreaterThan(Integer value) {
            addCriterion("gno >", value, "gno");
            return (Criteria) this;
        }

        public Criteria andGnoGreaterThanOrEqualTo(Integer value) {
            addCriterion("gno >=", value, "gno");
            return (Criteria) this;
        }

        public Criteria andGnoLessThan(Integer value) {
            addCriterion("gno <", value, "gno");
            return (Criteria) this;
        }

        public Criteria andGnoLessThanOrEqualTo(Integer value) {
            addCriterion("gno <=", value, "gno");
            return (Criteria) this;
        }

        public Criteria andGnoIn(List<Integer> values) {
            addCriterion("gno in", values, "gno");
            return (Criteria) this;
        }

        public Criteria andGnoNotIn(List<Integer> values) {
            addCriterion("gno not in", values, "gno");
            return (Criteria) this;
        }

        public Criteria andGnoBetween(Integer value1, Integer value2) {
            addCriterion("gno between", value1, value2, "gno");
            return (Criteria) this;
        }

        public Criteria andGnoNotBetween(Integer value1, Integer value2) {
            addCriterion("gno not between", value1, value2, "gno");
            return (Criteria) this;
        }

        public Criteria andNo1IsNull() {
            addCriterion("no1 is null");
            return (Criteria) this;
        }

        public Criteria andNo1IsNotNull() {
            addCriterion("no1 is not null");
            return (Criteria) this;
        }

        public Criteria andNo1EqualTo(Integer value) {
            addCriterion("no1 =", value, "no1");
            return (Criteria) this;
        }

        public Criteria andNo1NotEqualTo(Integer value) {
            addCriterion("no1 <>", value, "no1");
            return (Criteria) this;
        }

        public Criteria andNo1GreaterThan(Integer value) {
            addCriterion("no1 >", value, "no1");
            return (Criteria) this;
        }

        public Criteria andNo1GreaterThanOrEqualTo(Integer value) {
            addCriterion("no1 >=", value, "no1");
            return (Criteria) this;
        }

        public Criteria andNo1LessThan(Integer value) {
            addCriterion("no1 <", value, "no1");
            return (Criteria) this;
        }

        public Criteria andNo1LessThanOrEqualTo(Integer value) {
            addCriterion("no1 <=", value, "no1");
            return (Criteria) this;
        }

        public Criteria andNo1In(List<Integer> values) {
            addCriterion("no1 in", values, "no1");
            return (Criteria) this;
        }

        public Criteria andNo1NotIn(List<Integer> values) {
            addCriterion("no1 not in", values, "no1");
            return (Criteria) this;
        }

        public Criteria andNo1Between(Integer value1, Integer value2) {
            addCriterion("no1 between", value1, value2, "no1");
            return (Criteria) this;
        }

        public Criteria andNo1NotBetween(Integer value1, Integer value2) {
            addCriterion("no1 not between", value1, value2, "no1");
            return (Criteria) this;
        }

        public Criteria andNo2IsNull() {
            addCriterion("no2 is null");
            return (Criteria) this;
        }

        public Criteria andNo2IsNotNull() {
            addCriterion("no2 is not null");
            return (Criteria) this;
        }

        public Criteria andNo2EqualTo(Integer value) {
            addCriterion("no2 =", value, "no2");
            return (Criteria) this;
        }

        public Criteria andNo2NotEqualTo(Integer value) {
            addCriterion("no2 <>", value, "no2");
            return (Criteria) this;
        }

        public Criteria andNo2GreaterThan(Integer value) {
            addCriterion("no2 >", value, "no2");
            return (Criteria) this;
        }

        public Criteria andNo2GreaterThanOrEqualTo(Integer value) {
            addCriterion("no2 >=", value, "no2");
            return (Criteria) this;
        }

        public Criteria andNo2LessThan(Integer value) {
            addCriterion("no2 <", value, "no2");
            return (Criteria) this;
        }

        public Criteria andNo2LessThanOrEqualTo(Integer value) {
            addCriterion("no2 <=", value, "no2");
            return (Criteria) this;
        }

        public Criteria andNo2In(List<Integer> values) {
            addCriterion("no2 in", values, "no2");
            return (Criteria) this;
        }

        public Criteria andNo2NotIn(List<Integer> values) {
            addCriterion("no2 not in", values, "no2");
            return (Criteria) this;
        }

        public Criteria andNo2Between(Integer value1, Integer value2) {
            addCriterion("no2 between", value1, value2, "no2");
            return (Criteria) this;
        }

        public Criteria andNo2NotBetween(Integer value1, Integer value2) {
            addCriterion("no2 not between", value1, value2, "no2");
            return (Criteria) this;
        }

        public Criteria andNo3IsNull() {
            addCriterion("no3 is null");
            return (Criteria) this;
        }

        public Criteria andNo3IsNotNull() {
            addCriterion("no3 is not null");
            return (Criteria) this;
        }

        public Criteria andNo3EqualTo(Integer value) {
            addCriterion("no3 =", value, "no3");
            return (Criteria) this;
        }

        public Criteria andNo3NotEqualTo(Integer value) {
            addCriterion("no3 <>", value, "no3");
            return (Criteria) this;
        }

        public Criteria andNo3GreaterThan(Integer value) {
            addCriterion("no3 >", value, "no3");
            return (Criteria) this;
        }

        public Criteria andNo3GreaterThanOrEqualTo(Integer value) {
            addCriterion("no3 >=", value, "no3");
            return (Criteria) this;
        }

        public Criteria andNo3LessThan(Integer value) {
            addCriterion("no3 <", value, "no3");
            return (Criteria) this;
        }

        public Criteria andNo3LessThanOrEqualTo(Integer value) {
            addCriterion("no3 <=", value, "no3");
            return (Criteria) this;
        }

        public Criteria andNo3In(List<Integer> values) {
            addCriterion("no3 in", values, "no3");
            return (Criteria) this;
        }

        public Criteria andNo3NotIn(List<Integer> values) {
            addCriterion("no3 not in", values, "no3");
            return (Criteria) this;
        }

        public Criteria andNo3Between(Integer value1, Integer value2) {
            addCriterion("no3 between", value1, value2, "no3");
            return (Criteria) this;
        }

        public Criteria andNo3NotBetween(Integer value1, Integer value2) {
            addCriterion("no3 not between", value1, value2, "no3");
            return (Criteria) this;
        }

        public Criteria andNo4IsNull() {
            addCriterion("no4 is null");
            return (Criteria) this;
        }

        public Criteria andNo4IsNotNull() {
            addCriterion("no4 is not null");
            return (Criteria) this;
        }

        public Criteria andNo4EqualTo(Integer value) {
            addCriterion("no4 =", value, "no4");
            return (Criteria) this;
        }

        public Criteria andNo4NotEqualTo(Integer value) {
            addCriterion("no4 <>", value, "no4");
            return (Criteria) this;
        }

        public Criteria andNo4GreaterThan(Integer value) {
            addCriterion("no4 >", value, "no4");
            return (Criteria) this;
        }

        public Criteria andNo4GreaterThanOrEqualTo(Integer value) {
            addCriterion("no4 >=", value, "no4");
            return (Criteria) this;
        }

        public Criteria andNo4LessThan(Integer value) {
            addCriterion("no4 <", value, "no4");
            return (Criteria) this;
        }

        public Criteria andNo4LessThanOrEqualTo(Integer value) {
            addCriterion("no4 <=", value, "no4");
            return (Criteria) this;
        }

        public Criteria andNo4In(List<Integer> values) {
            addCriterion("no4 in", values, "no4");
            return (Criteria) this;
        }

        public Criteria andNo4NotIn(List<Integer> values) {
            addCriterion("no4 not in", values, "no4");
            return (Criteria) this;
        }

        public Criteria andNo4Between(Integer value1, Integer value2) {
            addCriterion("no4 between", value1, value2, "no4");
            return (Criteria) this;
        }

        public Criteria andNo4NotBetween(Integer value1, Integer value2) {
            addCriterion("no4 not between", value1, value2, "no4");
            return (Criteria) this;
        }

        public Criteria andNo5IsNull() {
            addCriterion("no5 is null");
            return (Criteria) this;
        }

        public Criteria andNo5IsNotNull() {
            addCriterion("no5 is not null");
            return (Criteria) this;
        }

        public Criteria andNo5EqualTo(Integer value) {
            addCriterion("no5 =", value, "no5");
            return (Criteria) this;
        }

        public Criteria andNo5NotEqualTo(Integer value) {
            addCriterion("no5 <>", value, "no5");
            return (Criteria) this;
        }

        public Criteria andNo5GreaterThan(Integer value) {
            addCriterion("no5 >", value, "no5");
            return (Criteria) this;
        }

        public Criteria andNo5GreaterThanOrEqualTo(Integer value) {
            addCriterion("no5 >=", value, "no5");
            return (Criteria) this;
        }

        public Criteria andNo5LessThan(Integer value) {
            addCriterion("no5 <", value, "no5");
            return (Criteria) this;
        }

        public Criteria andNo5LessThanOrEqualTo(Integer value) {
            addCriterion("no5 <=", value, "no5");
            return (Criteria) this;
        }

        public Criteria andNo5In(List<Integer> values) {
            addCriterion("no5 in", values, "no5");
            return (Criteria) this;
        }

        public Criteria andNo5NotIn(List<Integer> values) {
            addCriterion("no5 not in", values, "no5");
            return (Criteria) this;
        }

        public Criteria andNo5Between(Integer value1, Integer value2) {
            addCriterion("no5 between", value1, value2, "no5");
            return (Criteria) this;
        }

        public Criteria andNo5NotBetween(Integer value1, Integer value2) {
            addCriterion("no5 not between", value1, value2, "no5");
            return (Criteria) this;
        }

        public Criteria andNo6IsNull() {
            addCriterion("no6 is null");
            return (Criteria) this;
        }

        public Criteria andNo6IsNotNull() {
            addCriterion("no6 is not null");
            return (Criteria) this;
        }

        public Criteria andNo6EqualTo(Integer value) {
            addCriterion("no6 =", value, "no6");
            return (Criteria) this;
        }

        public Criteria andNo6NotEqualTo(Integer value) {
            addCriterion("no6 <>", value, "no6");
            return (Criteria) this;
        }

        public Criteria andNo6GreaterThan(Integer value) {
            addCriterion("no6 >", value, "no6");
            return (Criteria) this;
        }

        public Criteria andNo6GreaterThanOrEqualTo(Integer value) {
            addCriterion("no6 >=", value, "no6");
            return (Criteria) this;
        }

        public Criteria andNo6LessThan(Integer value) {
            addCriterion("no6 <", value, "no6");
            return (Criteria) this;
        }

        public Criteria andNo6LessThanOrEqualTo(Integer value) {
            addCriterion("no6 <=", value, "no6");
            return (Criteria) this;
        }

        public Criteria andNo6In(List<Integer> values) {
            addCriterion("no6 in", values, "no6");
            return (Criteria) this;
        }

        public Criteria andNo6NotIn(List<Integer> values) {
            addCriterion("no6 not in", values, "no6");
            return (Criteria) this;
        }

        public Criteria andNo6Between(Integer value1, Integer value2) {
            addCriterion("no6 between", value1, value2, "no6");
            return (Criteria) this;
        }

        public Criteria andNo6NotBetween(Integer value1, Integer value2) {
            addCriterion("no6 not between", value1, value2, "no6");
            return (Criteria) this;
        }

        public Criteria andBonusIsNull() {
            addCriterion("bonus is null");
            return (Criteria) this;
        }

        public Criteria andBonusIsNotNull() {
            addCriterion("bonus is not null");
            return (Criteria) this;
        }

        public Criteria andBonusEqualTo(Integer value) {
            addCriterion("bonus =", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusNotEqualTo(Integer value) {
            addCriterion("bonus <>", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusGreaterThan(Integer value) {
            addCriterion("bonus >", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusGreaterThanOrEqualTo(Integer value) {
            addCriterion("bonus >=", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusLessThan(Integer value) {
            addCriterion("bonus <", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusLessThanOrEqualTo(Integer value) {
            addCriterion("bonus <=", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusIn(List<Integer> values) {
            addCriterion("bonus in", values, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusNotIn(List<Integer> values) {
            addCriterion("bonus not in", values, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusBetween(Integer value1, Integer value2) {
            addCriterion("bonus between", value1, value2, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusNotBetween(Integer value1, Integer value2) {
            addCriterion("bonus not between", value1, value2, "bonus");
            return (Criteria) this;
        }

        public Criteria andFirstCountIsNull() {
            addCriterion("first_count is null");
            return (Criteria) this;
        }

        public Criteria andFirstCountIsNotNull() {
            addCriterion("first_count is not null");
            return (Criteria) this;
        }

        public Criteria andFirstCountEqualTo(String value) {
            addCriterion("first_count =", value, "firstCount");
            return (Criteria) this;
        }

        public Criteria andFirstCountNotEqualTo(String value) {
            addCriterion("first_count <>", value, "firstCount");
            return (Criteria) this;
        }

        public Criteria andFirstCountGreaterThan(String value) {
            addCriterion("first_count >", value, "firstCount");
            return (Criteria) this;
        }

        public Criteria andFirstCountGreaterThanOrEqualTo(String value) {
            addCriterion("first_count >=", value, "firstCount");
            return (Criteria) this;
        }

        public Criteria andFirstCountLessThan(String value) {
            addCriterion("first_count <", value, "firstCount");
            return (Criteria) this;
        }

        public Criteria andFirstCountLessThanOrEqualTo(String value) {
            addCriterion("first_count <=", value, "firstCount");
            return (Criteria) this;
        }

        public Criteria andFirstCountLike(String value) {
            addCriterion("first_count like", value, "firstCount");
            return (Criteria) this;
        }

        public Criteria andFirstCountNotLike(String value) {
            addCriterion("first_count not like", value, "firstCount");
            return (Criteria) this;
        }

        public Criteria andFirstCountIn(List<String> values) {
            addCriterion("first_count in", values, "firstCount");
            return (Criteria) this;
        }

        public Criteria andFirstCountNotIn(List<String> values) {
            addCriterion("first_count not in", values, "firstCount");
            return (Criteria) this;
        }

        public Criteria andFirstCountBetween(String value1, String value2) {
            addCriterion("first_count between", value1, value2, "firstCount");
            return (Criteria) this;
        }

        public Criteria andFirstCountNotBetween(String value1, String value2) {
            addCriterion("first_count not between", value1, value2, "firstCount");
            return (Criteria) this;
        }

        public Criteria andFirstAmountIsNull() {
            addCriterion("first_amount is null");
            return (Criteria) this;
        }

        public Criteria andFirstAmountIsNotNull() {
            addCriterion("first_amount is not null");
            return (Criteria) this;
        }

        public Criteria andFirstAmountEqualTo(String value) {
            addCriterion("first_amount =", value, "firstAmount");
            return (Criteria) this;
        }

        public Criteria andFirstAmountNotEqualTo(String value) {
            addCriterion("first_amount <>", value, "firstAmount");
            return (Criteria) this;
        }

        public Criteria andFirstAmountGreaterThan(String value) {
            addCriterion("first_amount >", value, "firstAmount");
            return (Criteria) this;
        }

        public Criteria andFirstAmountGreaterThanOrEqualTo(String value) {
            addCriterion("first_amount >=", value, "firstAmount");
            return (Criteria) this;
        }

        public Criteria andFirstAmountLessThan(String value) {
            addCriterion("first_amount <", value, "firstAmount");
            return (Criteria) this;
        }

        public Criteria andFirstAmountLessThanOrEqualTo(String value) {
            addCriterion("first_amount <=", value, "firstAmount");
            return (Criteria) this;
        }

        public Criteria andFirstAmountLike(String value) {
            addCriterion("first_amount like", value, "firstAmount");
            return (Criteria) this;
        }

        public Criteria andFirstAmountNotLike(String value) {
            addCriterion("first_amount not like", value, "firstAmount");
            return (Criteria) this;
        }

        public Criteria andFirstAmountIn(List<String> values) {
            addCriterion("first_amount in", values, "firstAmount");
            return (Criteria) this;
        }

        public Criteria andFirstAmountNotIn(List<String> values) {
            addCriterion("first_amount not in", values, "firstAmount");
            return (Criteria) this;
        }

        public Criteria andFirstAmountBetween(String value1, String value2) {
            addCriterion("first_amount between", value1, value2, "firstAmount");
            return (Criteria) this;
        }

        public Criteria andFirstAmountNotBetween(String value1, String value2) {
            addCriterion("first_amount not between", value1, value2, "firstAmount");
            return (Criteria) this;
        }

        public Criteria andSecondCoountIsNull() {
            addCriterion("second_coount is null");
            return (Criteria) this;
        }

        public Criteria andSecondCoountIsNotNull() {
            addCriterion("second_coount is not null");
            return (Criteria) this;
        }

        public Criteria andSecondCoountEqualTo(String value) {
            addCriterion("second_coount =", value, "secondCoount");
            return (Criteria) this;
        }

        public Criteria andSecondCoountNotEqualTo(String value) {
            addCriterion("second_coount <>", value, "secondCoount");
            return (Criteria) this;
        }

        public Criteria andSecondCoountGreaterThan(String value) {
            addCriterion("second_coount >", value, "secondCoount");
            return (Criteria) this;
        }

        public Criteria andSecondCoountGreaterThanOrEqualTo(String value) {
            addCriterion("second_coount >=", value, "secondCoount");
            return (Criteria) this;
        }

        public Criteria andSecondCoountLessThan(String value) {
            addCriterion("second_coount <", value, "secondCoount");
            return (Criteria) this;
        }

        public Criteria andSecondCoountLessThanOrEqualTo(String value) {
            addCriterion("second_coount <=", value, "secondCoount");
            return (Criteria) this;
        }

        public Criteria andSecondCoountLike(String value) {
            addCriterion("second_coount like", value, "secondCoount");
            return (Criteria) this;
        }

        public Criteria andSecondCoountNotLike(String value) {
            addCriterion("second_coount not like", value, "secondCoount");
            return (Criteria) this;
        }

        public Criteria andSecondCoountIn(List<String> values) {
            addCriterion("second_coount in", values, "secondCoount");
            return (Criteria) this;
        }

        public Criteria andSecondCoountNotIn(List<String> values) {
            addCriterion("second_coount not in", values, "secondCoount");
            return (Criteria) this;
        }

        public Criteria andSecondCoountBetween(String value1, String value2) {
            addCriterion("second_coount between", value1, value2, "secondCoount");
            return (Criteria) this;
        }

        public Criteria andSecondCoountNotBetween(String value1, String value2) {
            addCriterion("second_coount not between", value1, value2, "secondCoount");
            return (Criteria) this;
        }

        public Criteria andSecondAmountIsNull() {
            addCriterion("second_amount is null");
            return (Criteria) this;
        }

        public Criteria andSecondAmountIsNotNull() {
            addCriterion("second_amount is not null");
            return (Criteria) this;
        }

        public Criteria andSecondAmountEqualTo(String value) {
            addCriterion("second_amount =", value, "secondAmount");
            return (Criteria) this;
        }

        public Criteria andSecondAmountNotEqualTo(String value) {
            addCriterion("second_amount <>", value, "secondAmount");
            return (Criteria) this;
        }

        public Criteria andSecondAmountGreaterThan(String value) {
            addCriterion("second_amount >", value, "secondAmount");
            return (Criteria) this;
        }

        public Criteria andSecondAmountGreaterThanOrEqualTo(String value) {
            addCriterion("second_amount >=", value, "secondAmount");
            return (Criteria) this;
        }

        public Criteria andSecondAmountLessThan(String value) {
            addCriterion("second_amount <", value, "secondAmount");
            return (Criteria) this;
        }

        public Criteria andSecondAmountLessThanOrEqualTo(String value) {
            addCriterion("second_amount <=", value, "secondAmount");
            return (Criteria) this;
        }

        public Criteria andSecondAmountLike(String value) {
            addCriterion("second_amount like", value, "secondAmount");
            return (Criteria) this;
        }

        public Criteria andSecondAmountNotLike(String value) {
            addCriterion("second_amount not like", value, "secondAmount");
            return (Criteria) this;
        }

        public Criteria andSecondAmountIn(List<String> values) {
            addCriterion("second_amount in", values, "secondAmount");
            return (Criteria) this;
        }

        public Criteria andSecondAmountNotIn(List<String> values) {
            addCriterion("second_amount not in", values, "secondAmount");
            return (Criteria) this;
        }

        public Criteria andSecondAmountBetween(String value1, String value2) {
            addCriterion("second_amount between", value1, value2, "secondAmount");
            return (Criteria) this;
        }

        public Criteria andSecondAmountNotBetween(String value1, String value2) {
            addCriterion("second_amount not between", value1, value2, "secondAmount");
            return (Criteria) this;
        }

        public Criteria andThirdCountIsNull() {
            addCriterion("third_count is null");
            return (Criteria) this;
        }

        public Criteria andThirdCountIsNotNull() {
            addCriterion("third_count is not null");
            return (Criteria) this;
        }

        public Criteria andThirdCountEqualTo(String value) {
            addCriterion("third_count =", value, "thirdCount");
            return (Criteria) this;
        }

        public Criteria andThirdCountNotEqualTo(String value) {
            addCriterion("third_count <>", value, "thirdCount");
            return (Criteria) this;
        }

        public Criteria andThirdCountGreaterThan(String value) {
            addCriterion("third_count >", value, "thirdCount");
            return (Criteria) this;
        }

        public Criteria andThirdCountGreaterThanOrEqualTo(String value) {
            addCriterion("third_count >=", value, "thirdCount");
            return (Criteria) this;
        }

        public Criteria andThirdCountLessThan(String value) {
            addCriterion("third_count <", value, "thirdCount");
            return (Criteria) this;
        }

        public Criteria andThirdCountLessThanOrEqualTo(String value) {
            addCriterion("third_count <=", value, "thirdCount");
            return (Criteria) this;
        }

        public Criteria andThirdCountLike(String value) {
            addCriterion("third_count like", value, "thirdCount");
            return (Criteria) this;
        }

        public Criteria andThirdCountNotLike(String value) {
            addCriterion("third_count not like", value, "thirdCount");
            return (Criteria) this;
        }

        public Criteria andThirdCountIn(List<String> values) {
            addCriterion("third_count in", values, "thirdCount");
            return (Criteria) this;
        }

        public Criteria andThirdCountNotIn(List<String> values) {
            addCriterion("third_count not in", values, "thirdCount");
            return (Criteria) this;
        }

        public Criteria andThirdCountBetween(String value1, String value2) {
            addCriterion("third_count between", value1, value2, "thirdCount");
            return (Criteria) this;
        }

        public Criteria andThirdCountNotBetween(String value1, String value2) {
            addCriterion("third_count not between", value1, value2, "thirdCount");
            return (Criteria) this;
        }

        public Criteria andThirdAmountIsNull() {
            addCriterion("third_amount is null");
            return (Criteria) this;
        }

        public Criteria andThirdAmountIsNotNull() {
            addCriterion("third_amount is not null");
            return (Criteria) this;
        }

        public Criteria andThirdAmountEqualTo(String value) {
            addCriterion("third_amount =", value, "thirdAmount");
            return (Criteria) this;
        }

        public Criteria andThirdAmountNotEqualTo(String value) {
            addCriterion("third_amount <>", value, "thirdAmount");
            return (Criteria) this;
        }

        public Criteria andThirdAmountGreaterThan(String value) {
            addCriterion("third_amount >", value, "thirdAmount");
            return (Criteria) this;
        }

        public Criteria andThirdAmountGreaterThanOrEqualTo(String value) {
            addCriterion("third_amount >=", value, "thirdAmount");
            return (Criteria) this;
        }

        public Criteria andThirdAmountLessThan(String value) {
            addCriterion("third_amount <", value, "thirdAmount");
            return (Criteria) this;
        }

        public Criteria andThirdAmountLessThanOrEqualTo(String value) {
            addCriterion("third_amount <=", value, "thirdAmount");
            return (Criteria) this;
        }

        public Criteria andThirdAmountLike(String value) {
            addCriterion("third_amount like", value, "thirdAmount");
            return (Criteria) this;
        }

        public Criteria andThirdAmountNotLike(String value) {
            addCriterion("third_amount not like", value, "thirdAmount");
            return (Criteria) this;
        }

        public Criteria andThirdAmountIn(List<String> values) {
            addCriterion("third_amount in", values, "thirdAmount");
            return (Criteria) this;
        }

        public Criteria andThirdAmountNotIn(List<String> values) {
            addCriterion("third_amount not in", values, "thirdAmount");
            return (Criteria) this;
        }

        public Criteria andThirdAmountBetween(String value1, String value2) {
            addCriterion("third_amount between", value1, value2, "thirdAmount");
            return (Criteria) this;
        }

        public Criteria andThirdAmountNotBetween(String value1, String value2) {
            addCriterion("third_amount not between", value1, value2, "thirdAmount");
            return (Criteria) this;
        }

        public Criteria andGdateIsNull() {
            addCriterion("gdate is null");
            return (Criteria) this;
        }

        public Criteria andGdateIsNotNull() {
            addCriterion("gdate is not null");
            return (Criteria) this;
        }

        public Criteria andGdateEqualTo(Date value) {
            addCriterion("gdate =", value, "gdate");
            return (Criteria) this;
        }

        public Criteria andGdateNotEqualTo(Date value) {
            addCriterion("gdate <>", value, "gdate");
            return (Criteria) this;
        }

        public Criteria andGdateGreaterThan(Date value) {
            addCriterion("gdate >", value, "gdate");
            return (Criteria) this;
        }

        public Criteria andGdateGreaterThanOrEqualTo(Date value) {
            addCriterion("gdate >=", value, "gdate");
            return (Criteria) this;
        }

        public Criteria andGdateLessThan(Date value) {
            addCriterion("gdate <", value, "gdate");
            return (Criteria) this;
        }

        public Criteria andGdateLessThanOrEqualTo(Date value) {
            addCriterion("gdate <=", value, "gdate");
            return (Criteria) this;
        }

        public Criteria andGdateIn(List<Date> values) {
            addCriterion("gdate in", values, "gdate");
            return (Criteria) this;
        }

        public Criteria andGdateNotIn(List<Date> values) {
            addCriterion("gdate not in", values, "gdate");
            return (Criteria) this;
        }

        public Criteria andGdateBetween(Date value1, Date value2) {
            addCriterion("gdate between", value1, value2, "gdate");
            return (Criteria) this;
        }

        public Criteria andGdateNotBetween(Date value1, Date value2) {
            addCriterion("gdate not between", value1, value2, "gdate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table destiny_info
     *
     * @mbggenerated do_not_delete_during_merge Tue Jul 26 11:58:35 KST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}