package my.random.bean;

import java.util.Calendar;
import java.util.Date;


public class DestinyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destiny_info.gno
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    private Integer gno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destiny_info.no1
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    private Integer no1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destiny_info.no2
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    private Integer no2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destiny_info.no3
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    private Integer no3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destiny_info.no4
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    private Integer no4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destiny_info.no5
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    private Integer no5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destiny_info.no6
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    private Integer no6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destiny_info.bonus
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    private Integer bonus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destiny_info.first_count
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    private String firstCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destiny_info.first_amount
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    private String firstAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destiny_info.second_coount
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    private String secondCoount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destiny_info.second_amount
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    private String secondAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destiny_info.third_count
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    private String thirdCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destiny_info.third_amount
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    private String thirdAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destiny_info.gdate
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    private Date gdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destiny_info.gno
     *
     * @return the value of destiny_info.gno
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public Integer getGno() {
        return gno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destiny_info.gno
     *
     * @param gno the value for destiny_info.gno
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public void setGno(Integer gno) {
        this.gno = gno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destiny_info.no1
     *
     * @return the value of destiny_info.no1
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public Integer getNo1() {
        return no1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destiny_info.no1
     *
     * @param no1 the value for destiny_info.no1
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public void setNo1(Integer no1) {
        this.no1 = no1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destiny_info.no2
     *
     * @return the value of destiny_info.no2
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public Integer getNo2() {
        return no2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destiny_info.no2
     *
     * @param no2 the value for destiny_info.no2
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public void setNo2(Integer no2) {
        this.no2 = no2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destiny_info.no3
     *
     * @return the value of destiny_info.no3
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public Integer getNo3() {
        return no3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destiny_info.no3
     *
     * @param no3 the value for destiny_info.no3
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public void setNo3(Integer no3) {
        this.no3 = no3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destiny_info.no4
     *
     * @return the value of destiny_info.no4
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public Integer getNo4() {
        return no4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destiny_info.no4
     *
     * @param no4 the value for destiny_info.no4
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public void setNo4(Integer no4) {
        this.no4 = no4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destiny_info.no5
     *
     * @return the value of destiny_info.no5
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public Integer getNo5() {
        return no5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destiny_info.no5
     *
     * @param no5 the value for destiny_info.no5
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public void setNo5(Integer no5) {
        this.no5 = no5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destiny_info.no6
     *
     * @return the value of destiny_info.no6
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public Integer getNo6() {
        return no6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destiny_info.no6
     *
     * @param no6 the value for destiny_info.no6
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public void setNo6(Integer no6) {
        this.no6 = no6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destiny_info.bonus
     *
     * @return the value of destiny_info.bonus
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public Integer getBonus() {
        return bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destiny_info.bonus
     *
     * @param bonus the value for destiny_info.bonus
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public void setBonus(Integer bonus) {
        this.bonus = bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destiny_info.first_count
     *
     * @return the value of destiny_info.first_count
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public String getFirstCount() {
        return firstCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destiny_info.first_count
     *
     * @param firstCount the value for destiny_info.first_count
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public void setFirstCount(String firstCount) {
        this.firstCount = firstCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destiny_info.first_amount
     *
     * @return the value of destiny_info.first_amount
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public String getFirstAmount() {
        return firstAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destiny_info.first_amount
     *
     * @param firstAmount the value for destiny_info.first_amount
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public void setFirstAmount(String firstAmount) {
        this.firstAmount = firstAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destiny_info.second_coount
     *
     * @return the value of destiny_info.second_coount
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public String getSecondCoount() {
        return secondCoount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destiny_info.second_coount
     *
     * @param secondCoount the value for destiny_info.second_coount
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public void setSecondCoount(String secondCoount) {
        this.secondCoount = secondCoount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destiny_info.second_amount
     *
     * @return the value of destiny_info.second_amount
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public String getSecondAmount() {
        return secondAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destiny_info.second_amount
     *
     * @param secondAmount the value for destiny_info.second_amount
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public void setSecondAmount(String secondAmount) {
        this.secondAmount = secondAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destiny_info.third_count
     *
     * @return the value of destiny_info.third_count
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public String getThirdCount() {
        return thirdCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destiny_info.third_count
     *
     * @param thirdCount the value for destiny_info.third_count
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public void setThirdCount(String thirdCount) {
        this.thirdCount = thirdCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destiny_info.third_amount
     *
     * @return the value of destiny_info.third_amount
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public String getThirdAmount() {
        return thirdAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destiny_info.third_amount
     *
     * @param thirdAmount the value for destiny_info.third_amount
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public void setThirdAmount(String thirdAmount) {
        this.thirdAmount = thirdAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destiny_info.gdate
     *
     * @return the value of destiny_info.gdate
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public Date getGdate() {
        return gdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destiny_info.gdate
     *
     * @param gdate the value for destiny_info.gdate
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    public void setGdate(Date gdate) {
        this.gdate = gdate;
    }
}