package my.random.bean;

import java.util.Calendar;
import java.util.Date;

public class Luckylog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_log.seq
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    private Long seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_log.gno
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    private Integer gno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_log.nick
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    private String nick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_log.grade
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_log.no1
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    private Integer no1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_log.no2
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    private Integer no2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_log.no3
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    private Integer no3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_log.no4
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    private Integer no4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_log.no5
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    private Integer no5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_log.no6
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    private Integer no6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_log.regdate
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    private Date regdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_log.seq
     *
     * @return the value of lucky_log.seq
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    public Long getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_log.seq
     *
     * @param seq the value for lucky_log.seq
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    public void setSeq(Long seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_log.gno
     *
     * @return the value of lucky_log.gno
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    public Integer getGno() {
        return gno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_log.gno
     *
     * @param gno the value for lucky_log.gno
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    public void setGno(Integer gno) {
        this.gno = gno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_log.nick
     *
     * @return the value of lucky_log.nick
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_log.nick
     *
     * @param nick the value for lucky_log.nick
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    public void setNick(String nick) {
        this.nick = nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_log.grade
     *
     * @return the value of lucky_log.grade
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_log.grade
     *
     * @param grade the value for lucky_log.grade
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_log.no1
     *
     * @return the value of lucky_log.no1
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    public Integer getNo1() {
        return no1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_log.no1
     *
     * @param no1 the value for lucky_log.no1
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    public void setNo1(Integer no1) {
        this.no1 = no1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_log.no2
     *
     * @return the value of lucky_log.no2
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    public Integer getNo2() {
        return no2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_log.no2
     *
     * @param no2 the value for lucky_log.no2
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    public void setNo2(Integer no2) {
        this.no2 = no2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_log.no3
     *
     * @return the value of lucky_log.no3
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    public Integer getNo3() {
        return no3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_log.no3
     *
     * @param no3 the value for lucky_log.no3
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    public void setNo3(Integer no3) {
        this.no3 = no3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_log.no4
     *
     * @return the value of lucky_log.no4
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    public Integer getNo4() {
        return no4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_log.no4
     *
     * @param no4 the value for lucky_log.no4
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    public void setNo4(Integer no4) {
        this.no4 = no4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_log.no5
     *
     * @return the value of lucky_log.no5
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    public Integer getNo5() {
        return no5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_log.no5
     *
     * @param no5 the value for lucky_log.no5
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    public void setNo5(Integer no5) {
        this.no5 = no5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_log.no6
     *
     * @return the value of lucky_log.no6
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    public Integer getNo6() {
        return no6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_log.no6
     *
     * @param no6 the value for lucky_log.no6
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    public void setNo6(Integer no6) {
        this.no6 = no6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_log.regdate
     *
     * @return the value of lucky_log.regdate
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    public Date getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_log.regdate
     *
     * @param regdate the value for lucky_log.regdate
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }
    private long regdatetime = 0;
    public long getRegdatetime(){
    	Calendar c = Calendar.getInstance();
    	c.setTime(getRegdate());
    	return c.getTimeInMillis()/1000;
    }
}