package my.random.bean;

import java.util.Date;

public class Member extends MemberKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.email
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.passwd
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.uname
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.phone
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.state
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.gender
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.age_range_min
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    private Integer ageRangeMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.age_range_max
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    private Integer ageRangeMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.regdate
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    private Date regdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.recent_login_date
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    private Date recentLoginDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.email
     *
     * @return the value of member.email
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.email
     *
     * @param email the value for member.email
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.passwd
     *
     * @return the value of member.passwd
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.passwd
     *
     * @param passwd the value for member.passwd
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.uname
     *
     * @return the value of member.uname
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.uname
     *
     * @param uname the value for member.uname
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.phone
     *
     * @return the value of member.phone
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.phone
     *
     * @param phone the value for member.phone
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.state
     *
     * @return the value of member.state
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.state
     *
     * @param state the value for member.state
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.gender
     *
     * @return the value of member.gender
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.gender
     *
     * @param gender the value for member.gender
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.age_range_min
     *
     * @return the value of member.age_range_min
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public Integer getAgeRangeMin() {
        return ageRangeMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.age_range_min
     *
     * @param ageRangeMin the value for member.age_range_min
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public void setAgeRangeMin(Integer ageRangeMin) {
        this.ageRangeMin = ageRangeMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.age_range_max
     *
     * @return the value of member.age_range_max
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public Integer getAgeRangeMax() {
        return ageRangeMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.age_range_max
     *
     * @param ageRangeMax the value for member.age_range_max
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public void setAgeRangeMax(Integer ageRangeMax) {
        this.ageRangeMax = ageRangeMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.regdate
     *
     * @return the value of member.regdate
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public Date getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.regdate
     *
     * @param regdate the value for member.regdate
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.recent_login_date
     *
     * @return the value of member.recent_login_date
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public Date getRecentLoginDate() {
        return recentLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.recent_login_date
     *
     * @param recentLoginDate the value for member.recent_login_date
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public void setRecentLoginDate(Date recentLoginDate) {
        this.recentLoginDate = recentLoginDate;
    }
}