package my.random.bean;

public class MemberKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.uid
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.udiv
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    private String udiv;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.uid
     *
     * @return the value of member.uid
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.uid
     *
     * @param uid the value for member.uid
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.udiv
     *
     * @return the value of member.udiv
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public String getUdiv() {
        return udiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.udiv
     *
     * @param udiv the value for member.udiv
     *
     * @mbggenerated Fri Jul 24 02:20:09 KST 2020
     */
    public void setUdiv(String udiv) {
        this.udiv = udiv;
    }
}