package my.random.mapper;

import java.util.List;

import my.random.bean.DestinyInfo;
import my.random.bean.DestinyInfoExample;

import org.apache.ibatis.annotations.Param;

public interface DestinyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    int countByExample(DestinyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    int deleteByExample(DestinyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    int deleteByPrimaryKey(Integer gno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    int insert(DestinyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    int insertSelective(DestinyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    List<DestinyInfo> selectByExample(DestinyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    DestinyInfo selectByPrimaryKey(Integer gno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    int updateByExampleSelective(@Param("record") DestinyInfo record, @Param("example") DestinyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    int updateByExample(@Param("record") DestinyInfo record, @Param("example") DestinyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    int updateByPrimaryKeySelective(DestinyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destiny_info
     *
     * @mbggenerated Tue Jul 26 11:58:35 KST 2016
     */
    int updateByPrimaryKey(DestinyInfo record);

    DestinyInfo getLastDestinyInfo();
}