package my.random.mapper;

import java.util.List;
import my.random.bean.Luckylog;
import my.random.bean.LuckylogExample;
import org.apache.ibatis.annotations.Param;

public interface LuckylogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    int countByExample(LuckylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    int deleteByExample(LuckylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    int deleteByPrimaryKey(Long seq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    int insert(Luckylog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    int insertSelective(Luckylog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    List<Luckylog> selectByExample(LuckylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    Luckylog selectByPrimaryKey(Long seq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    int updateByExampleSelective(@Param("record") Luckylog record, @Param("example") LuckylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    int updateByExample(@Param("record") Luckylog record, @Param("example") LuckylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    int updateByPrimaryKeySelective(Luckylog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbggenerated Fri Jul 29 18:15:32 KST 2016
     */
    int updateByPrimaryKey(Luckylog record);
}